### ISSUE TITLE
Some help with the setup ..

### ISSUE THREAD

**Issue by mascatul** [jackreimers/injact#3]
Hello,

I need some help with the setup and general use .

I cloned your repo locally , i included in my VS solution your projects.
I created a class named "DiContext" that inherits from your Context and attach it to Node in the scene .
I created an installer (node installer don't work for me or i didn't understand how use it because the extension "FromNode" requires other type of receiver "'ObjectBindingBuilder' does not contain a definition for 'FromNode' and the best extension method overload 'ObjectBindingStatementExtensions.FromNode(ObjectBindingStatement, Node)' requires a receiver of type 'Injact.ObjectBindingStatement'
") .

On Init of the Context there is an error about "nativeInstallers" being null and ofc nothing is injected

Here is the installer

````
public partial class PlayerInstaller: Installer
{
    public PlayerInstaller(DiContainer container) : base(container)
    {
    }

    public override void InstallBindings()
    {
        // Bind a class to the container.
        _container.Bind<PlayerCharacter>().AsSingleton().Finalise();
        
        //_container.Bind<Inventorypage>().AsSingleton().Finalise();
    }
}`

```

Any help will be much appreciated
Thanks,

**Comment by jackreimers** [comment]
Hey @mascatul,

Thanks for raising an issue!

I've just pushed a change which should fix the issue with nativeInstallers being null and the issue with FromNode not working. Please pull down the latest changes and let me know if this resolves the issue for you, if not I will investigate further.

Thanks!

**Comment by mascatul** [comment]
Hey @jackreimers ,

Thanks for taking your time to check this.

Seems ok now up to some point but after restarting Godot i got some strange error about some doubled keys after that Godot crashes and cant re-build project

```
  /root/godot/modules/mono/glue/GodotSharp/GodotSharp/Core/NativeInterop/ExceptionUtils.cs:112 - System.ArgumentException: An item with the same key has already been added. Key: Injact.Godot.Context
     at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
     at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
     at Godot.Bridge.ScriptManagerBridge.ScriptTypeBiMap.Add(IntPtr scriptPtr, Type scriptType) in /root/godot/modules/mono/glue/GodotSharp/GodotSharp/Core/Bridge/ScriptManagerBridge.types.cs:line 23
     at Godot.Bridge.ScriptManagerBridge.TryReloadRegisteredScriptWithClass(IntPtr scriptPtr) in /root/godot/modules/mono/glue/GodotSharp/GodotSharp/Core/Bridge/ScriptManagerBridge.cs:line 587
  /root/godot/modules/mono/glue/GodotSharp/GodotSharp/Core/NativeInterop/ExceptionUtils.cs:112 - System.ArgumentException: An item with the same key has already been added. Key: Injact.Godot.NodeInstaller
     at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
     at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
     at Godot.Bridge.ScriptManagerBridge.ScriptTypeBiMap.Add(IntPtr scriptPtr, Type scriptType) in /root/godot/modules/mono/glue/GodotSharp/GodotSharp/Core/Bridge/ScriptManagerBridge.types.cs:line 23
     at Godot.Bridge.ScriptManagerBridge.TryReloadRegisteredScriptWithClass(IntPtr scriptPtr) in /root/godot/modules/mono/glue/GodotSharp/GodotSharp/Core/Bridge/ScriptManagerBridge.cs:line 587
--- Debugging process stopped ---
```
The nodes look like this  (Context and Installer):
![image](https://github.com/jackreimers/Injact/assets/4599369/bae76098-0961-4d42-bb45-320c39afc4e1)

```
public partial class PlayerInstaller : NodeInstaller
{

    [Export] private Node Player;
    [Export] private Node UI;
    public override void InstallBindings()
    {
        // Bind a class to the container.
        _container.Bind<PlayerCharacter>().FromNode(Player).Finalise();
        _container.Bind<UiInventorySettings>().FromNode(UI).Finalise();
    }
}
```
Thank you,

**Comment by jackreimers** [comment]
@mascatul no worries, I'm just trying to replicate the issue you're having now.

Would you be able to post your DiContext file as well please?

**Comment by mascatul** [comment]
Hi ,

i tried both inheriting from your context or creating my own the result is the same


```
using Injact;
using Injact.Godot;
using System;

public partial class DiContext : Context
{

}
```

or

```
using Injact;
using Injact.Godot;
using System.Linq;
using Time = Injact.Time;

public partial class DiContext : Node
{
    [Inject] private readonly ILogger _logger = null!;

    [ExportCategory("Initialisation")]
    [Export] private bool searchForNodes = true;
    [Export] private bool searchForInstallers = true;

    [ExportCategory("References")]
    [Export] private Node[] injectTargets = Array.Empty<Node>();
    [Export] private NodeInstaller[] installers = Array.Empty<NodeInstaller>();

    [ExportCategory("Logging")]
    [Export] private bool logDebugging = true;
    [Export] private bool logTracing = true;

    private DiContainer _container = null!;
    private ContainerOptions? _options;
    private Injector _injector = null!;

    private Node[]? nodeBuffer;
    private IInstaller[] nativeInstallers = Array.Empty<IInstaller>();

    public override void _EnterTree()
    {
        //Note that logging settings will not be updated at runtime
        _container = new DiContainer(_options ?? new ContainerOptions
        {
            LogDebugging = logDebugging,
            LogTracing = logTracing,
            LoggingProvider = new LoggingProvider()
        });

        _injector = _container.Resolve<Injector>(this);
        _injector.InjectInto(this);

        TrySearchForInstallers();
        TryResolveAllInScene();

        foreach (var installer in nativeInstallers.Concat(installers))
        {
            _logger.LogInformation($"Installing bindings for {installer.GetType().Name}.");

            _injector.InjectInto(installer);
            installer.InstallBindings();
        }

        _container.ProcessPendingBindings();

        foreach (var target in injectTargets)
        {
            _injector.InjectInto(target);
        }
    }

    public override void _Process(double delta)
    {
        Time.Delta = (float)delta;
        Time.TriggerUpdate();
        Time.TriggerLateUpdate();

        base._Process(delta);
    }

    protected void SetContainerOptions(ContainerOptions options)
    {
        _options = options;
    }

    protected void AddInstallers(params IInstaller[] value)
    {
        nativeInstallers = value;
    }

    private void TrySearchForInstallers()
    {
        if (!searchForInstallers)
        {
            return;
        }

        _logger.LogWarning("Search for installers is enabled, user set installers will be ignored.", installers.Any());

        nodeBuffer ??= GodotHelper.GetAllChildNodes(GetTree().Root);
        installers = nodeBuffer
            .Where(s => s is NodeInstaller)
            .Cast<NodeInstaller>()
            .ToArray();

        _logger.LogWarning("Could not find any node installers in scene.", !installers.Any());
    }

    private void TryResolveAllInScene()
    {
        if (!searchForNodes)
        {
            return;
        }

        _logger.LogWarning("Search for nodes is enabled, user set nodes will be ignored.", injectTargets.Any());

        nodeBuffer ??= GodotHelper.GetAllChildNodes(GetTree().Root);
        injectTargets = nodeBuffer;
    }
}
```

**Comment by jackreimers** [comment]
Hey @mascatul,

I'm not able to reproduce this but from reading the error messages it looks like the context and node installer are getting bound to the container multiple times when they should not be. Please double check that you are not manually binding the context or node installer anywhere in your code, they do not need to be bound.

Installers can be added to the container using the "Installers" parameter under "References" in the inspector properties of your context or by having the context at the root of your scene and turning "Search for Installers" on:

![image](https://github.com/jackreimers/Injact/assets/10693364/7401064e-daf4-431c-b8fa-553391530b89)

The context does not need to be added to the container at all, this is done automatically during startup when the context initialises the DI container.

If you've double checked and can't find anywhere that this is being done, would you be able to create a public repo (or a private one and give me access) with the code and Godot project that you are getting this error with so I can troubleshoot the issue a bit easier?

Thanks for your patience!

**Comment by jackreimers** [comment]
@mascatul do you still need help with this issue?

**Comment by mascatul** [comment]
Hi Jack,

No , its fine, seems there is something in my project i tested on fresh empty project seems fine. 


Thanks,
